### PR TITLE
feat: add VfsRootAccesshelper for IntelliJ 2021.3 compatibility

### LINKED ISSUE #122: Provider VfsRootAccessHelper for IntelliJ 2021.3 compatibility
As 2021.3 broke in `VfsRootAccess.allowRootAccess`

### PR DESCRIPTION
**Pull request by jeffmaury**
Fixes #122

Signed-off-by: Jeff MAURY <jmaury@redhat.com>

### CODE REVIEW

**Review by lstocchi — COMMENTED** [review]
Why is it inside the test folder? Shouldn't it be in main? This could be re-use somewhere else.
Then the constructor is private but the method are not static.

**Comment by jeffmaury** [comment]
> Why is it inside the test folder? Shouldn't it be in main? This could be re-use somewhere else. Then the constructor is private but the method are not static.

This is only required during tests. Will fix the static issue

**Comment by lstocchi** [comment]
> This is only required during tests. Will fix the static issue

We use that thing in other plugin tests so if you put it in common test is not visible outside... or is there a way to see that when importing IJ-common as dep?

**Comment by jeffmaury** [comment]
> > This is only required during tests. Will fix the static issue
> 
> We use that thing in other plugin tests so if you put it in common test is not visible outside... or is there a way to see that when importing IJ-common as dep?

No you can reuse them see https://github.com/redhat-developer/intellij-openshift-connector/blob/13654c4378efeae7445f9f5ab50ce80bf63b1b8f/build.gradle#L74

**Review by lstocchi — APPROVED** [review]
LGTM

**Pull request merged**
