### PR TITLE
fix: add ansi escape chars handling to process handler

### PR DESCRIPTION
**Pull request by lstocchi**
This is needed for https://github.com/redhat-developer/intellij-knative/issues/169 :crossed_fingers:

### CODE REVIEW

**Comment by jeffmaury** [comment]
@lstocchi I think we can close this one no ?

**Comment by lstocchi** [comment]
Yes, definitely. I think IJ knative is not even developed anymore

**Comment by adietish** [comment]
I'd keep this opened to better reflect the presence of a defect. True, we don't develop it any more but who knows, maybe somebody else would pick it up?

**Comment by jeffmaury** [comment]
> @jeffmaury, @lstocchi: I'd keep this opened to better reflect the presence of a defect. True, we don't develop it any more but who knows, maybe somebody else would pick it up?

From my POV this issue should be kept open but I don't think it make sense to keep this 2 years old PR (as closing the PR does not remove the contributed code)

**Comment by adietish** [comment]
> From my POV this issue should be kept open but I don't think it make sense to keep this 2 years old PR (as closing the PR does not remove the contributed code)

@jeffmaury: sorry, my bad, erroneously thought this to be an issue, not a PR.

**Pull request closed without merging**
