### PR TITLE
feat: add generic resource model

### PR DESCRIPTION
**Pull request by lstocchi**
This is linked to https://github.com/redhat-developer/intellij-tekton/pull/405

### CODE REVIEW

**Review by jeffmaury — COMMENTED** [review]
LGTM but I have a question: as intellij-common has a dependency on the kubernetes client, I think there is a similar class there so can't we use it ?

**Comment by lstocchi** [comment]
> LGTM but I have a question: as intellij-common has a dependency on the kubernetes client, I think there is a similar class there so can't we use it ?

I can't find anything close to this in the kubernetes client. The only one generic is `CustomResourceDefinition` but it doesn't seem to me that take any advantage to our workflow, the opposite. There was some class you were referring to?

**Comment by jeffmaury** [comment]
> 
> 
> > LGTM but I have a question: as intellij-common has a dependency on the kubernetes client, I think there is a similar class there so can't we use it ?
> 
> I can't find anything close to this in the kubernetes client. The only one generic is `CustomResourceDefinition` but it doesn't seem to me that take any advantage to our workflow, the opposite. There was some class you were referring to?

`io.fabric8.kubernetes.client.CustomResource` is the class to look for but it is abstract but maybe can be reused. @adietish may help

**Comment by lstocchi** [comment]
> `io.fabric8.kubernetes.client.CustomResource` is the class to look for but it is abstract but maybe can be reused. 

I looked into it but i'm not fully convinced. This class is useful if you want to create a resource which is already defined when writing the code. The costructor uses annotations to retrieve the infos it needs (like `@Group`, `@Version`, `@Plural`, ..) and uses those values to create a new customResource (CRD, apiVersion, and everything else). 
In my case I don't have those infos in advance as i could deserialize everything into a generic resource, it can be a pipeline/pod/kservice. For me, this is just a wrapper that can contain a resource and that can be used to extract the infos I need. Everything is saved as jsonnode so each yaml section is sent as it is and one can be free to extract the data he wants. In my case labels inside the metadata, in another case could be something else.

**Comment by jeffmaury** [comment]
> 
> 
> > `io.fabric8.kubernetes.client.CustomResource` is the class to look for but it is abstract but maybe can be reused.
> 
> I looked into it but i'm not fully convinced. This class is useful if you want to create a resource which is already defined when writing the code. The costructor uses annotations to retrieve the infos it needs (like `@Group`, `@Version`, `@Plural`, ..) and uses those values to create a new customResource (CRD, apiVersion, and everything else).
> In my case I don't have those infos in advance as i could deserialize everything into a generic resource, it can be a pipeline/pod/kservice. For me, this is just a wrapper that can contain a resource and that can be used to extract the infos I need. Everything is saved as jsonnode so each yaml section is sent as it is and one can be free to extract the data he wants. In my case labels inside the metadata, in another case could be something else.

OK. Good to go as is

**Review by jeffmaury — APPROVED** [review]

**Pull request merged**
