### PR TITLE
feat: update executeInterminal with TerminalExecutionConsole

### PR DESCRIPTION
**Pull request by lstocchi**
So, this is the final solution for me.
https://github.com/redhat-developer/intellij-common/pull/91 has this issue  https://github.com/redhat-developer/intellij-common/pull/91#issuecomment-926700233
https://github.com/redhat-developer/intellij-common/pull/99 is too hacky, i needed to override many classes and i'm afraid it can be a problem in future releases. If they change something we need to edit it again.

This PR is the one that requires less changes even in the other plugins (method signature remains the same) and the TerminalExecutionConsole will be kept as it is for the moment. No breaking changes in the near future :crossed_fingers: 
The overall behavior/experience will remain the same as it is today so users wouldn't see much differences.
It allows user interactions.

I tried it with Tekton and Knative and it seems ok. IJ-RSP should be the most problematic one to change.
Let me know what you think:

### CODE REVIEW

**Review by jeffmaury — APPROVED** [review]
LGTM.
Tested with OpenShift Connector on Windows and display is ok

**Comment by lstocchi** [comment]
@jeffmaury in IJ-RSP there were some problems with some actions (e.g start rsp server worked fine but start/stop a normal server didn't display the output correctly). I found out that some missing `\r` before `\n` could lead to this issue. By adding a custom reader which add `\r` when needed it solves the problem and the output is displayed correctly.

I read that in Windows `\r\n` marks the end of line so this solution should work in Windows as well but can you please give it another try? Thanks

**Review by jeffmaury — APPROVED** [review]
LGTM.
Tested on Windows with RSP and output of server (Wildfly) is ok

**Review by adietish — APPROVED** [review]

**Comment by adietish** [comment]
@lstocchi as I can see you integrated the `BaseOutputReader.Options()` that solved the problem for me but apparently need a custom reader. Can you please elaborate?

**Comment by lstocchi** [comment]
> @lstocchi as I can see you integrated the `BaseOutputReader.Options()` that solved the problem for me but apparently need a custom reader. Can you please elaborate?

That is needed to clean the output of some action in IJ RSP https://github.com/redhat-developer/intellij-rsp/pull/110
While starting a rsp server worked fine, starting/stopping a normal server produced an output with a wrong indentation and it was unreadable. I found out that some incomplete end line chars can lead to that. The custom reader is used to fix it. If it find some `\n` which is not preceded by `\r`, it adds it. This solves the issue

**Pull request merged**
