### PR TITLE
feat: allow ConfigWatcher to watch several files (#236)

### LINKED ISSUE #236: ConfigWatcher should be able to handle multiple config files
depends on #235

https://github.com/redhat-developer/intellij-kubernetes/issues/779 requires the ability to watch all the files that are used to configure the client (see https://github.com/fabric8io/kubernetes-client/pull/6295)

### PR DESCRIPTION
**Pull request by adietish**
fixes #236

### CODE REVIEW

**Comment by adietish** [comment]
@sbouchet please review.

**Comment by sbouchet** [comment]
code looks ok. what's the process to actually test it ? compile locally then use that build in kuberntes with multiple kubeconfig files ?

**Review by sbouchet — COMMENTED** [review]
code looks ok. what's the process to actually test it ? compile locally then use that build in kuberntes with multiple kubeconfig files ?

**Review by sbouchet — APPROVED** [review]
works fine with multiples or single files.

**Pull request merged**
