### PR TITLE
feat: Return basic cluster information

### LINKED ISSUE #76: A utility to return basic cluster information for telemetry
The following information will be recorded:

- Kubernetes version
- flag for OpenShift/Kubernetes cluster type
- OpenShift version (may be absent on OCP4 and non admin access)

### PR DESCRIPTION
**Pull request by jeffmaury**
Fixes #76

Signed-off-by: Jeff MAURY <jmaury@redhat.com>

### CODE REVIEW

**Comment by lstocchi** [comment]
Tried with an openshift cluster found on the ui-clusters slack channel and i got 
image
Major and minor are null

**Comment by jeffmaury** [comment]
> 
> 
> Tried with an openshift cluster found on the ui-clusters slack channel and i got
> image
> Major and minor are null.
> 
> More info about the cluster Server Version: 4.8.0-0.nightly-2021-05-26-071911
> Kubernetes Version: v1.21.0-rc.0+936c9e2

Upstream issue: https://github.com/fabric8io/kubernetes-client/issues/3174

**Review by lstocchi — APPROVED** [review]
LGTM

**Review by sbouchet — APPROVED** [review]
LGTM.

**Pull request merged**
