### PR TITLE
feat: Add new method to detect if current theme/LAF is dark or not

### LINKED ISSUE #95: Add new method to know if theme is dark or not

### PR DESCRIPTION
**Pull request by jeffmaury**
Fixes #95

Signed-off-by: Jeff MAURY <jmaury@redhat.com>

### CODE REVIEW

**Review by lstocchi — APPROVED** [review]
LGTM ... why do you need this? And why only dark?
Only doubt is the name, even if this is made by IJ itself. For me Darcula is dark but it returns false :thinking: , it only works with high contrast theme

**Comment by jeffmaury** [comment]
Because I need to select different icons if theme is dark or not.

Ex:

image

**Comment by lstocchi** [comment]
> Because I need to select different icons if theme is dark or not.

Can't you use an IJ icon so they handle the color based on the theme? E.g `AllIcons.General.Add` 
image

BTW in your image it seems to me you're using darcula as theme, if so it doesn't work for me .
`lafInfo instanceof UIThemeBasedLookAndFeelInfo && ((UIThemeBasedLookAndFeelInfo)lafInfo).getTheme().isDark()` returns false because lafInfo is not a UIThemeBasedLookAndFeelInfo

image

**Comment by jeffmaury** [comment]
Using JB icons is not an option as I have other icons to deal with. But seems you pointed an issue, will update

**Review by lstocchi — APPROVED** [review]
Works fine :+1:

**Pull request merged**
