### PR TITLE
feat: add silentMode to DownloadHelper (#121)

### LINKED ISSUE #121: DownloadHelper should offer a silent mode
We should have a way to silently download a CLI as they are most of the time mandatory and internal to the implementation and users may be lost answering the question

### PR DESCRIPTION
**Pull request by lstocchi**
it resolves #121

### CODE REVIEW

**Review by jeffmaury — COMMENTED** [review]
For better compatibility, I think the parameter should be part of the tool json file.
Now I did not test your stuff but it looks to me that there will be still a dialog be shown and I think this should be hidden or a background task to make sure user does not cancel it.

**Comment by jeffmaury** [comment]
TBH having something visible will always lead to user complaining. And user should see a Loading item in the tree, so it's my preference 👍

**Comment by lstocchi** [comment]
Now nothing is shown. Only a label (`2 processes running` in my case as knative is downloading kn and func clis) in the bottom right. If clicked all processes are displayed but not cancellable.
background-2

**Review by jeffmaury — CHANGES_REQUESTED** [review]
The only issue is that the UI will be frozen because the code is executed in the UI thread and once the background task is launched, the UI thread will be blocked on `command.get()`

**Review by jeffmaury — APPROVED** [review]
LGTM

**Pull request merged**
